
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'dev-server'
    static_configs:
      - targets: ['dev-server:8000']
        labels:
          service: 'api'
          
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        
  - job_name: 'postgres'
    static_configs:
      - targets: ['db:9187']
        
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:9121']

rule_files:
  - '/etc/prometheus/alerts.rules'
